### ISSUE TITLE
Responsive images with simpleParallax

### ISSUE THREAD

**Issue by aldo-freeosk** [geosigno/simpleParallax#12]
I'm using picturefill to load different images in conjunction with simpleParallax and it's working great on Chrome/Safari, but the images don't load on Firefox. I'm guessing the issue is that a div wrapping the img tag inside the picture element is not OK with Firefox. I'm not sure if there's a workaround. Thanks

This is how I have everything set up:
```
<section class="joy-divider">
    <picture>
      <source data-srcset="desktop-img.jpg 2x" media="(min-width: 600px)">
      <source data-srcset="mobile-img.jpg 2x">
      <img class="lazyload" src="" data-src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="">
    </picture>
</section>
```

```
var parallaxImages = $('.joy-divider img');
new simpleParallax(parallaxImages, {
  delay: 0.75,
  scale: 1.3,
  transition: 'cubic-bezier(0,0,0,1)'
});
```

**Comment by geosigno** [comment]
Please update the plugin to 4.2.1. This issue should now be fixed.

**Comment by geosigno** [comment]
I'm closing this now, feel free to re-open it if you still encounter the issue.
