### ISSUE TITLE
Uncaught TypeError: this.element.addEventListener is not a function

### ISSUE THREAD

**Issue by Juniorr452** [geosigno/simpleParallax#18]
Hey! I'm using simpleParallax with a script tag and I can't make it work with the example code:

```
var image = document.getElementsByClassName('parallax');
new simpleParallax(image);
```
I'm using [5.0.1](https://github.com/geosigno/simpleParallax/releases/tag/5.0.1). Tried 5.0 earlier and got #17. 

Here's a print of the error message:

![](https://i.imgur.com/g9cLb4Q.png)

**Comment by geosigno** [comment]
This should be fixed with [5.0.2](https://github.com/geosigno/simpleParallax/releases/tag/5.0.2)
Thanks for reporting this issue.
