### ISSUE TITLE
Parallax effect is shaking/not smooth on MS Edge

### ISSUE THREAD

**Issue by K4T** [geosigno/simpleParallax#20]
On MS Edge parallax effect is jerky/not smooth. You can easily reproduce it on the official page with examples.

OS: Windows 10 Home x64
Browser: MS Edge 44.17763.1.0

It is super fine on FireFox and Chrome.

**Comment by geosigno** [comment]
Yes I already noticed this. I'll try to give a new look when I have time.
But I guess this is one of the many reasons Edge will die soon.

**Comment by geosigno** [comment]
I don't see any option to avoid this.

**Comment by apsolut** [comment]
This should be in documentation that you dont support `Latest` IE that isnt close to EOL.
