### ISSUE TITLE
Reinitialization

### ISSUE THREAD

**Issue by podhy** [geosigno/simpleParallax#22]
Hello,
is there any way to reinitialize simpleParallax?

I've got collapsible element (using bootstrap) in my page and some parallax images under this element. If i show content of collapsible element, parallax stopped working for these elements. 

So I thought i will destroy simpleParallax and create new instance but withnout effect.

Is there any way?

**Comment by geosigno** [comment]
Hi podhy,
This is weird that parallax stop working because of accordion, can you share an example? or a codepen?
You should be able to destroy the instance and to init simpleParallax again. The same way you did at the first initialization. Again I would need some example here to spot the issue.

**Comment by geosigno** [comment]
Closing this as no feedback received.
