### ISSUE TITLE
The parallax effect stops across breakpoints 

### ISSUE THREAD

**Issue by Faycal79** [geosigno/simpleParallax#24]
When I set a breakpoint (ex. 1024) and I reduce the window the effect correctly ends. When I enlarge the window the effect doesn't restarts.

It may be useful that, with overflow:true, orientation:down and scale:1 the "sliding effects" is maintained and that it starts at "0" point transform: translate3d(0px, 0px, 0px);

**Comment by geosigno** [comment]
I'm currently working on that one. I'll keep you posted.

**Comment by geosigno** [comment]
The breakpoint parameter has been removed with the [5.2.0](https://github.com/geosigno/simpleParallax/releases/tag/5.2.0) release. This should be managed outside the simpleParallax plugin.
