### ISSUE TITLE
Remove generated DIV

### ISSUE THREAD

**Issue by inalbisdev** [geosigno/simpleParallax#25]
Hello!

Is it possible to remove the div that nests the image? It gives problems if you want to maintain the aspect ratio of the image.

Thank you

**Comment by geosigno** [comment]
Hi,

The div allows to have the overflow hidden around the image to get the parallax effect. If you change the param to overflow at false, you won't have this div, but the overflow will be visible.

Hope it help, if not please send me a codepen so i can check the aspect ratio issue.

**Comment by geosigno** [comment]
Closing this issue as now feedback received.
