### ISSUE TITLE
Apply transition after setting it to the right position (translate3d and scale)

### ISSUE THREAD

**Issue by zhrance** [geosigno/simpleParallax#26]
Hi, First of all I want to say that your javascript with images works pretty neat. It's the first proper code I find for parallax scrolling with images which are not set on the background with CSS :)

I got the following issue, when I open a page with parallax you see the image transitioning to the right position with translate3d and scale. Which feels kinda buggy. Is there a way to set the translate3d and scale without applying a transition but adding the transition when the image is already set to the right position and you start scrolling? Would love to hear, this transition on load is some kind of deal breaker when you apply parallax to a header at the top of a page.

**Comment by geosigno** [comment]
Hi zhrance,

First, thanks for you interest in simpleParallax, really appreciated it. 

And then thanks again for spotting this, after some time I feel like I was considering this buggy effect as the default behavior... Feel good to have external feedback to tackle those.

This has been commit on develop, and we'll be soon merged with master.

**Comment by zhrance** [comment]
You are more than welcome. I can imagine you consider the buggy effect as a feature after some time :) Although I would love to see it fixed. Let me know if I can help/support you. My main knowledge is HTML/CSS. Also applied your parallax in some projects with responsive images, lazy loading and using placeholder where the images has position:absolute.

**Comment by zhrance** [comment]
Hi Geosigno, how are you doing? Any updates regarding this "issue"? :)

**Comment by geosigno** [comment]
This has just been released with the [5.2.0](https://github.com/geosigno/simpleParallax/releases/tag/5.2.0).
