### ISSUE TITLE
Custom scroll container option

### ISSUE THREAD

**Issue by cicsolutions** [geosigno/simpleParallax#32]
Hi, and thanks for such a great parallax plugin!  

My site template requires an HTML structure that tracks user scrolling by a wrapper div and not the window. 

Is it possible to set a custom scroll container for simpleParallax?  Thanks again!

**Comment by geosigno** [comment]
That seems doable, I’ll work on that.

**Comment by geosigno** [comment]
The new [5.2.0](https://github.com/geosigno/simpleParallax/releases/tag/5.2.0) release adds a _customContainer_ parameter.
