### ISSUE TITLE
is it possible to use the Simpleparallax for <div> tag and background image?

### ISSUE THREAD

**Issue by skalanter** [geosigno/simpleParallax#38]
Hi,

is it possible to use Simpleparallax for <div> tag and background image?

I want to add parallax to fancy image box (like Icon Box with the background color):

![image](https://user-images.githubusercontent.com/8671492/73024883-c231dc80-3e43-11ea-8ac1-2deded12dd9f.png)

**Comment by geosigno** [comment]
Hi skalanter,

simpleParallax has been initially developed to have parallax effect for non-background images... The reason being a lot of parallax effect are already available for background images.

**Comment by skalanter** [comment]
So, great...
Thank you for explaining.
All the best
